export const ADD_CHAPTER = 'ADD_CHAPTER';
export const ADD_SUBSECTION = 'ADD_SUBSECTION';
export const TOGGLE_SUBSECTION = 'TOGGLE_SUBSECTION';

export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST';
export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS';
export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE';
